### ISSUE TITLE
请问不是企业微信的管理员可以用吗？只有企微机器人的Webhook地址，回调URL，EncodingAESKey和Token

### ISSUE THREAD

**Issue by ladypiapia** [Gyronee/chatgpt-bizwechat-bot#1]
<img width="597" alt="截屏2022-12-11 12 09 23" src="https://user-images.githubusercontent.com/36269124/206885943-9e54256a-0fa9-41f8-89f9-23fd799bce36.png">
由于不是公司企微的管理员，只能创建机器人拿到机器人的相关信息，但无法拿到corp_id  和 agent_id

**Comment by Gyronee** [comment]
不行的，因为发消息给用户需要 access_token 的认证，access_token 的获取接口需要 corp_id 和 secret 进行认证.  每一条请求的消息体解密也需要用到 corp_id, 这个参数是必须拿到的。

agent_id 是发消息给用户的接口需要传输的参数。

另外，如果能进入到配置回调的 url 的界面的话，agent_id 应该是能拿到的，就在前一个页面。secret 上面 就是 agent_id
<img width="310" alt="image" src="https://user-images.githubusercontent.com/4464307/206890458-5f2a1aff-bfff-4f7a-97ea-25824e7716b1.png">

**Comment by ladypiapia** [comment]
非常感谢回答，我去找同事问问
