### ISSUE TITLE
docker容器停止运行

### ISSUE THREAD

**Issue by cn0068** [Gyronee/chatgpt-bizwechat-bot#3]
请问用以下：
docker run -d --name wx-chatbot -p 8868:8868 -v :/wx-chatbot/config.yaml gyronee/chatgpt-bizwechat-bot:latest
发现docker容器停止运行，日志如下：
Traceback (most recent call last):
  File "/wx-chatbot/main.py", line 9, in <module>
    with open("config.yaml", "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'

**Comment by Gyronee** [comment]
-v :/wx-chatbot/config.yaml 这个地方应该提供你的配置文件
比如 -v /home/xxxx/config.yaml:/wx-chatbot/config.yaml

**Comment by cn0068** [comment]
> -v :/wx-chatbot/config.yaml 这个地方应该提供你的配置文件 比如 -v /home/xxxx/config.yaml:/wx-chatbot/config.yaml
再请教一下：
我用/docker/wx-chatbot/config.yaml:/wx-chatbot/config.yaml也是出错，config.yaml是自动生成的吧？docke,wx-chatbot目录已存在。
